[package]
name = "golem-rust"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
description = "Golem Rust tooling library that facilitates writing Golem backends in Rust"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
uuid = { version = "1.8.0", features = ["v4"], optional = true }
wit-bindgen = { version = "0.17.0", default-features = false, features = ["realloc"] }

[features]
default = ["uuid"]
uuid = ["dep:uuid"]

[package.metadata.component]
package = "golem:rust"

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
"golem:api" = { path = "wit/deps/golem" }
"golem:rpc" = { path = "wit/deps/wasm-rpc" }
"wasi:clocks" = { path = "wit/deps/clocks" }
"wasi:io" = { path = "wit/deps/io" }