[package]
name = "golem-rust"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem-rust"
description = "Golem Rust tooling library that facilitates writing Golem backends in Rust"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
golem-rust-macro = { path = "../golem-rust-macro", version = "0.0.0", optional = true }
serde = { version = "1.0.219", optional = true }
serde_json = { version = "1.0.140", optional = true }
uuid = { version = "1.15.1", features = ["v4"], optional = true }
wit-bindgen-rt = { version = "0.40.0", features = ["bitflags"] }

[features]
default = ["json", "macro", "uuid"]
json = ["dep:serde", "dep:serde_json"]
macro = ["dep:golem-rust-macro"]
uuid = ["dep:uuid"]

[package.metadata.component]
package = "golem:rust"

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
"golem:api" = { path = "wit/deps/golem-1.x" }
"golem:durability" = { path = "wit/deps/golem-durability" }
"golem:rdbms" = { path = "wit/deps/rdbms" }
"golem:rpc" = { path = "wit/deps/wasm-rpc" }
"wasi:clocks" = { path = "wit/deps/clocks" }
"wasi:io" = { path = "wit/deps/io" }
"wasi:http" = { path = "wit/deps/http" }
"wasi:random" = { path = "wit/deps/random" }
"wasi:cli" = { path = "wit/deps/cli" }
"wasi:filesystem" = { path = "wit/deps/filesystem" }
"wasi:sockets" = { path = "wit/deps/sockets" }
"wasi:blobstore" = { path = "wit/deps/blobstore" }
"wasi:keyvalue" = { path = "wit/deps/keyvalue" }
"wasi:logging" = { path = "wit/deps/logging" }
