[package]
name = "golem-rust-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
golem-rust = { path = "../golem-rust" }
heck = "0.5.0"
linkme = "0.3.26"
